version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_name
      
  django:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/django
      - static:/static
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - 80:80
    depends_on:
      - django

volumes:
  postgres_data:
  static: