version: '3.8'
services:
  django:
    env_file:
      - .env
    volumes:
      - static:/static
    build: .
    ports:
      - 8000:8000

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - 80:80
    depends_on:
      - django

volumes:
  static: