version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      
  django:
    env_file:
      - .env
    volumes:
      - .:/django
      - static:/static
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - 80:80
    depends_on:
      - django

volumes:
  postgres_data:
  static: