version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    volumes:
      - .:/django
    depends_on:
      - db
  
  test:
    build: .
    depends_on:
      - db
      - django
    profiles:
      - ['test']
    env_file:
      - .env.dev
    command:
      - /bin/sh
      - -c
      - |
        echo "Type checking: "
        mypy .

        echo "Unit tests:"
        python3 manage.py test

        echo "e2e tests: "
        python3 manage.py behave

volumes:
  postgres_data: